name: Build and SemVer Tag

on:
  push:
    branches:
      - main

jobs:
  bump-tag-version:
    name: Bump and Tag Version
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          cache: gradle

      - name: Build
        run: ./gradlew build

      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties

      - name: Bump and Tag Version
        id: bump-tag-version
        uses: jefflinse/pr-semver-bump@v1
        with:
          mode: bump
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          major-label: major release
          minor-label: minor release
          patch-label: patch release
          require-release-notes: true
          release-notes-prefix: ''
          release-notes-suffix: ''
          with-v: false

      - name: Report Tag Bump Activity
        run: |
          # One might be incined to think that another release workflow could pick up on
          # on.push.tags.'[0-9]+\.[0-9]+\.[0-9]+' but the event lacks 'startsWith(github.ref, 'refs/tags/')'
          # However, all the information for kicking a release after above potential semver bump is here. Thanks @Michionlion
          echo   Previous version: ${{ steps.bump-tag-version.outputs.old-version }}
          echo New bumped version: ${{ steps.bump-tag-version.outputs.version }}

      - name: Conditional Release Trigger
        uses: peter-evans/repository-dispatch@v1
        if: steps.bump-tag-version.outputs.version != ''
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: release-trigger
          client-payload: '{"semver": "${{ steps.bump-tag-version.outputs.version }}"}'
