name: Verify Build on Development Branch

# A quick verification build is run each time a commit is made to a branch that is not main.

on:
  push:
    branches-ignore:
      - main

jobs:
  verify-build:
    name: Verify build for commits to a PR branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          cache: gradle

      - name: Build
        run: ./gradlew build

      - name: Cleanup Gradle Cache
        # Remove select Gradle cache files from GitHub Actions context
        # to avoid potential problems with future Gradle tasks.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock ~/.gradle/caches/modules-2/gc.properties
