name: Build Main Branch

# A quick build verification for new code pushed to main branch. This will only trigger
# on a pull request merge since a GitHub rule has been applied to the main branch called
# "Require a pull request before merging". When enabled, all commits must be made to a
# non-protected branch and submitted via a pull request before they can be merged into a
# branch that matches this rule.

# If build in this action jobs is successful, then trigger the modular release action

on:
  push:
    branches:
      - main

jobs:
  verify-build-on-main:
    name: Verify build on merge PR to main branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          cache: gradle

      - name: Build
        run: ./gradlew build

      - name: Cleanup Gradle Cache
        # Remove select Gradle cache files from GitHub Actions context
        # to avoid potential problems with future Gradle tasks.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock ~/.gradle/caches/modules-2/gc.properties

      - name: Conditional Release Trigger
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: release-trigger
