name: Enqueued Release Info

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

jobs:
  check-pr:
    name: Validate Release Label and Notes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: jefflinse/pr-semver-bump@v1.3.2
        name: Validate Pull Request Metadata
        id: semver_bump_data
        with:
          mode: validate
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          major-label: major
          minor-label: minor
          patch-label: patch
          require-release-notes: true
          release-notes-prefix: "# Release notes"
          release-notes-suffix: ''
          with-v: false

      - name: Version Change Information
        run: |
          echo 'Potential version change enqueued:'
          echo "Current: ${{ steps.semver_bump_data.outputs.old-version }}"
          echo "    New: ${{ steps.semver_bump_data.outputs.version }}"
