name: Create Release

# Create release when triggered

on:
  repository_dispatch:
    types: [release-trigger]

jobs:
  Payload:
    runs-on: ubuntu-latest
    steps:
      - name: Release in Progress
        run: echo "A new release ${{ github.event.client_payload.semver }} is in progress."

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build release changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v2.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Dump Change Log
        run: echo ${{steps.github_release.outputs.changelog}}

      - name: Bump and Tag Version
        id: bump-tag-version
        uses: jefflinse/pr-semver-bump@v1.3.2
        with:
          mode: bump
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          major-label: major
          minor-label: minor
          patch-label: patch
          require-release-notes: true
          release-notes-prefix: "# Release notes"
          release-notes-suffix: ''
          with-v: false

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          cache: gradle

      - name: Build
        run: ./gradlew build

      - name: Build native
        run: ./gradlew build -PciSemVer=${{ github.event.client_payload.semver }} -Dquarkus.package.type=native -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel:21.2-java11

      - name: Compress native with UPX
        uses: crazy-max/ghaction-upx@v1.4.0
        with:
          version: v3.96
          files: |
            build/solver-${{ github.event.client_payload.semver }}-runner
        # args: --lzma
        # lzma, best, brute all give smaller size, but slow execution,
        # no arg, default, compression still compresses albeit
        # larger but larger with faster execution
        # https://github.com/upx/upx/blob/8d42b12117130b944023335cc2b76072c145db4d/src/main.cpp

      - name: List the built binaries
        run: ls -la build

      - name: Create Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          name: Release ${{ github.event.client_payload.semver }}
          tag_name: ${{ github.event.client_payload.semver }}
        #  body: ${{steps.github_release.outputs.changelog}}
          files: |
            LICENSE
            build/solver-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup Gradle Cache
        # Remove select Gradle cache files from GitHub Actions context
        # to avoid potential problems with future Gradle tasks.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock ~/.gradle/caches/modules-2/gc.properties
