name: Create Release

# Create release when triggered

on:
  repository_dispatch:
    types: [release-event-trigger]

jobs:
  Payload:
    runs-on: ubuntu-latest
    steps:
      - name: Bump and Tag Version
        id: semver_bump_data
        uses: jefflinse/pr-semver-bump@v1.3.2
        with:
          mode: validate
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          major-label: major
          minor-label: minor
          patch-label: patch
          require-release-notes: true
          release-notes-prefix: "# Release notes"
          release-notes-suffix: ''
          with-v: false

      - name: Release in Progress
        run: echo "A new release ${{ steps.semver_bump_data.outputs.version }} is in progress."

